spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lighthouse
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  thymeleaf:
    check-template: false
    check-template-location: false
